### PR TITLE
fix image display

### PR DESCRIPTION
**Pull request by CharlesLR-sekoia**

### CODE REVIEW

**Comment by CharlesLR-sekoia** [comment]
@Men-hau can you add the missing image sekoia_indicator.png as well please. Beware of maj cap.

**Comment by Men-hau** [comment]
@CharlesLR-sekoia The images of this documentation are in Cap.
I will then create a PR to rename all the images and same for `Sekoia_indicator.png` (that is already present in the [images repo](https://github.com/SEKOIA-IO/documentation/tree/main/docs/assets/intelligence_center))

**Comment by CharlesLR-sekoia** [comment]
@Men-hau I just did the work ;) see the files changed on this PR

**Comment by Men-hau** [comment]
@CharlesLR-sekoia It remains `Sekoia_indicator.png` to be renamed to `sekoia_indicator.png` and we are good to go ^^

**Review by Men-hau — APPROVED** [review]

**Pull request merged**
