### PR TITLE
Change Image and doc with good path and intake key instead of API key

### PR DESCRIPTION
**Pull request by pbivic**
related to https://sekoia8055.zendesk.com/agent/tickets/3441

### CODE REVIEW

**Review by rombernier — APPROVED** [review]

**Comment by pbivic** [comment]
Thanks @rombernier  🙏

**Comment by goudyj** [comment]
@pbivic the image should be modified also

**Comment by pbivic** [comment]
image
Already done ! :)

**Comment by goudyj** [comment]
Oups my bad ! :D Thanks a lot

**Pull request merged**
