### PR TITLE
Update to the latest MkDocs version

### PR DESCRIPTION
**Pull request by otetard**
This is a draft PR, please do not merge :).

### CODE REVIEW

**Comment by mortrevere** [comment]
It looks pretty but I find the new navigation less intuitive : clicking in the nav bar, then navigating with the list on the left, whereas it used to be all in the left panel (I think ?)

**Comment by gbossert** [comment]
I like it also, thank you.
Would it be possible to improve a bit the overall render of the homepage of the doc ?
image

**Comment by otetard** [comment]
> I like it also, thank you.
> Would it be possible to improve a bit the overall render of the homepage of the doc ?
> image

This is not the “real” default page. This page won’t be changed, we are still using `docsfront`’s landing page: https://docs.sekoia.io/

**Comment by otetard** [comment]
> It looks pretty but I find the new navigation less intuitive : clicking in the nav bar, then navigating with the list on the left, whereas it used to be all in the left panel (I think ?)

We can easily revert that change by disabling the `navigation.tabs` feature.

https://github.com/SEKOIA-IO/documentation/blob/e18b121e0c84691197b49aaba149f88d445d6452/mkdocs.yml#L106

**Review by celinequivy — APPROVED** [review]

**Review by mouniakhaled — APPROVED** [review]

**Pull request merged**
